//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.27 at 01:43:04 AM PST 
//


package MitchellClaimServiceUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.omg.CORBA.PUBLIC_MEMBER;


/**
 * <p>Java class for LossInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LossInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CauseOfLoss" type="{http://www.mitchell.com/examples/claim}CauseOfLossCode" minOccurs="0"/>
 *         &lt;element name="ReportedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LossDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LossInfoType", propOrder = {
    "causeOfLoss",
    "reportedDate",
    "lossDescription"
})
public class LossInfoType {

    @XmlElement(name = "CauseOfLoss")
    protected CauseOfLossCode causeOfLoss;
    @XmlElement(name = "ReportedDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reportedDate;
    @XmlElement(name = "LossDescription")
    protected String lossDescription;

    /**
     * Gets the value of the causeOfLoss property.
     * 
     * @return
     *     possible object is
     *     {@link CauseOfLossCode }
     *     
     */
    public CauseOfLossCode getCauseOfLoss() {
        return causeOfLoss;
    }

    /**
     * Sets the value of the causeOfLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link CauseOfLossCode }
     *     
     */
    public void setCauseOfLoss(CauseOfLossCode value) {
        this.causeOfLoss = value;
    }

    /**
     * Gets the value of the reportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReportedDate() {
        return reportedDate;
    }

    /**
     * Sets the value of the reportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReportedDate(XMLGregorianCalendar value) {
        this.reportedDate = value;
    }

    /**
     * Gets the value of the lossDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLossDescription() {
        return lossDescription;
    }

    /**
     * Sets the value of the lossDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLossDescription(String value) {
        this.lossDescription = value;
    }
    
    /**
     * customized method to verify content
     */
    
    public boolean equals(LossInfoType other){
    	if (other == null || other.getClass() != getClass()) {
			return false;
		}
    	
    	if (!reportedDate.equals(other.getReportedDate())){
    		System.out.println(">>"+reportedDate.toString());
    		System.out.println("<<"+other.reportedDate.toString());
    	}
    	
    	return (causeOfLoss.equals(other.getCauseOfLoss()) &&
    		    lossDescription.equals(other.getLossDescription()) &&
    		    reportedDate.equals(other.getReportedDate()));
    }
    

    public void display(){
    	System.out.println("CauseOfLoss: " + causeOfLoss);
    	System.out.println("LossDescription: " + lossDescription);
    	System.out.println("ReportedDate: " + (reportedDate == null? null: reportedDate.toString()));
    }
    
    public void updateWithInstance(LossInfoType other){
    	
    	if (other.causeOfLoss != null){
    		causeOfLoss = other.causeOfLoss;
    	}
    	
    	if (other.lossDescription != null){
    		lossDescription = other.lossDescription;
    	}
    	
    	if (other.reportedDate != null){
    		reportedDate = (XMLGregorianCalendar) other.reportedDate.clone();
    	}

    }
}
