//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.27 at 01:43:04 AM PST 
//


package MitchellClaimServiceUtils;

import javax.management.InstanceAlreadyExistsException;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.omg.PortableInterceptor.ObjectReferenceTemplateHelper;


/**
 * <p>Java class for MitchellClaimType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MitchellClaimType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ClaimantFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaimantLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.mitchell.com/examples/claim}StatusCode" minOccurs="0"/>
 *         &lt;element name="LossDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="LossInfo" type="{http://www.mitchell.com/examples/claim}LossInfoType" minOccurs="0"/>
 *         &lt;element name="AssignedAdjusterID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Vehicles" type="{http://www.mitchell.com/examples/claim}VehicleListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MitchellClaimType", propOrder = {
    "claimNumber",
    "claimantFirstName",
    "claimantLastName",
    "status",
    "lossDate",
    "lossInfo",
    "assignedAdjusterID",
    "vehicles"
})

@XmlRootElement(name = "MitchellClaim")
public class MitchellClaimType {

    @XmlElement(name = "ClaimNumber", required = true)
    protected String claimNumber;
    @XmlElement(name = "ClaimantFirstName")
    protected String claimantFirstName;
    @XmlElement(name = "ClaimantLastName")
    protected String claimantLastName;
    @XmlElement(name = "Status")
    protected StatusCode status;
    @XmlElement(name = "LossDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lossDate;
    @XmlElement(name = "LossInfo")
    protected LossInfoType lossInfo;
    @XmlElement(name = "AssignedAdjusterID")
    protected Long assignedAdjusterID;
    @XmlElement(name = "Vehicles")
    protected VehicleListType vehicles;

    /**
     * Gets the value of the claimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimNumber() {
        return claimNumber;
    }

    /**
     * Sets the value of the claimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimNumber(String value) {
        this.claimNumber = value;
    }

    /**
     * Gets the value of the claimantFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantFirstName() {
        return claimantFirstName;
    }

    /**
     * Sets the value of the claimantFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantFirstName(String value) {
        this.claimantFirstName = value;
    }

    /**
     * Gets the value of the claimantLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClaimantLastName() {
        return claimantLastName;
    }

    /**
     * Sets the value of the claimantLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClaimantLastName(String value) {
        this.claimantLastName = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCode }
     *     
     */
    public StatusCode getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCode }
     *     
     */
    public void setStatus(StatusCode value) {
        this.status = value;
    }

    /**
     * Gets the value of the lossDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLossDate() {
        return lossDate;
    }

    /**
     * Sets the value of the lossDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLossDate(XMLGregorianCalendar value) {
        this.lossDate = value;
    }

    /**
     * Gets the value of the lossInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LossInfoType }
     *     
     */
    public LossInfoType getLossInfo() {
        return lossInfo;
    }

    /**
     * Sets the value of the lossInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LossInfoType }
     *     
     */
    public void setLossInfo(LossInfoType value) {
        this.lossInfo = value;
    }

    /**
     * Gets the value of the assignedAdjusterID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAssignedAdjusterID() {
        return assignedAdjusterID;
    }

    /**
     * Sets the value of the assignedAdjusterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAssignedAdjusterID(Long value) {
        this.assignedAdjusterID = value;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleListType }
     *     
     */
    public VehicleListType getVehicles() {
        return vehicles;
    }

    /**
     * Sets the value of the vehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleListType }
     *     
     */
    public void setVehicles(VehicleListType value) {
        this.vehicles = value;
    }

    
    public void updateWithInstance(MitchellClaimType  other){
    	if (other.assignedAdjusterID != null){
    		this.assignedAdjusterID = other.assignedAdjusterID;
    	}
    	
    	if (other.claimantFirstName != null){
    		this.claimantFirstName = other.claimantFirstName;
    	}
    	
    	if (other.claimantLastName != null){
    		this.claimantLastName = other.claimantLastName;
    	}
    	
    	if (other.lossInfo != null){
    		this.lossInfo.updateWithInstance(other.lossInfo);
    	}
    	
    	if (other.lossDate != null){
    		this.lossDate = (XMLGregorianCalendar) other.lossDate.clone();
    	}
    	
    	if (other.status != null){
    		this.status = other.status;
    	}
    	
    	if (other.vehicles != null){
    		this.vehicles.updateWithInstance(other.vehicles);
    	}
    }
    /**
     * customized method to display claim content
     */
    public void display(){
    	System.out.println("ClaimNumber: " + claimNumber);
    	System.out.println("ClaimantFirstName: " + claimantFirstName);
    	System.out.println("ClaimantLastName: " + claimantLastName);
    	System.out.println("Status: " + status);
    	System.out.println("LossDate: " + (lossDate== null? null:lossDate.toString()));
    	System.out.println("AssignedAdjusterID: " + assignedAdjusterID);
    	System.out.println("******************** LossInfo ********************** " );
    	if (lossInfo != null) {
    		lossInfo.display();
    	}else{
    		System.out.println("LossInfo: null");
    	}
    	System.out.println("**************************************************** ");
    	System.out.println("******************** Vehicles ********************** ");
    	for (int i = 0; i < this.vehicles.getVehicleDetails().size(); ++i){
    		System.out.println("Vehicle" + Integer.toString(i) + "<---");
    		vehicles.getVehicleDetails().get(i).display();
    	}
    }
    
    /**
     * customize method to verify claim content
     */
    public boolean equals(MitchellClaimType other){
    	if (other == null || other.getClass() != getClass()) {
			return false;
		}
    	
    	if (!assignedAdjusterID.equals(other.getAssignedAdjusterID())){
    		System.out.println("assignedAdjusterID wrong");
    	}
    	
    	if (!claimantFirstName.equals(other.getClaimantFirstName())){
    		System.out.println("claimantFirstName");
    	}
    	
    	if (!claimantLastName.equals(other.getClaimantLastName())){
    		System.out.println("claimantLastName");
    	}
    	
    	if (!claimNumber.equals(other.getClaimNumber())){
    		System.out.println("claimNumber");
    	}
    	
    	if (!lossDate.equals(other.getLossDate())){
    		System.out.println("lossDate");
    	}
    	
    	if (!lossInfo.equals(other.lossInfo)){
    		System.out.println("lossInfo");
    	}
    	
    	if (!status.equals(other.getStatus())){
    		System.out.println("Status");
    	}
    	
    	if (!vehicles.equals(other.getVehicles())){
    		System.out.println("vehicles");
    	}
    	
    	return assignedAdjusterID.equals(other.getAssignedAdjusterID()) &&
			   claimantFirstName.equals(other.getClaimantFirstName()) &&
			   claimantLastName.equals(other.getClaimantLastName()) &&
			   claimNumber.equals(other.getClaimNumber()) &&
			   lossDate.equals(other.getLossDate()) && 
			   lossInfo.equals(other.getLossInfo()) &&
			   status.equals(other.getStatus()) &&
			   vehicles.equals(other.getVehicles());
    }
    
}
