//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.27 at 01:43:04 AM PST 
//

@XmlSchema(namespace = "http://www.mitchell.com/examples/claim", 
	xmlns = {
				@XmlNs(namespaceURI = "http://www.mitchell.com/examples/claim", prefix = "cla")  
			    //xmlns:xs="http://www.w3.org/2001/XMLSchema", 
			},
	elementFormDefault = XmlNsForm.QUALIFIED)

package MitchellClaimServiceUtils;

import javax.xml.bind.annotation.*;

