//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.27 at 01:43:04 AM PST 
//


package MitchellClaimServiceUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.PrimitiveIterator.OfDouble;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.omg.CORBA.ParameterModeHelper;
import org.omg.CosNaming.NamingContextExtPackage.AddressHelper;


/**
 * <p>Java class for VehicleInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ModelYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="MakeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EngineDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Vin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlateState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicPlateExpDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DamageDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Mileage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleInfoType", propOrder = {
	"vin",
	"modelYear",
    "makeDescription",
    "modelDescription",
    "engineDescription",
    "exteriorColor",
    "licPlate",
    "licPlateState",
    "licPlateExpDate",
    "damageDescription",
    "mileage"
})
public class VehicleInfoType {

    @XmlElement(name = "Vin")
    protected String vin;
    @XmlElement(name = "ModelYear")
    protected Integer modelYear;
    @XmlElement(name = "MakeDescription")
    protected String makeDescription;
    @XmlElement(name = "ModelDescription")
    protected String modelDescription;
    @XmlElement(name = "EngineDescription")
    protected String engineDescription;
    @XmlElement(name = "ExteriorColor")
    protected String exteriorColor;
    @XmlElement(name = "LicPlate")
    protected String licPlate;
    @XmlElement(name = "LicPlateState")
    protected String licPlateState;
    @XmlElement(name = "LicPlateExpDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar licPlateExpDate;
    @XmlElement(name = "DamageDescription")
    protected String damageDescription;
    @XmlElement(name = "Mileage")
    protected Integer mileage;

    /**
     * Gets the value of the modelYear property.
     * 
     */
    public Integer getModelYear() {
        return modelYear;
    }

    /**
     * Sets the value of the modelYear property.
     * 
     */
    public void setModelYear(int value) {
        this.modelYear = value;
    }

    /**
     * Gets the value of the makeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakeDescription() {
        return makeDescription;
    }

    /**
     * Sets the value of the makeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakeDescription(String value) {
        this.makeDescription = value;
    }

    /**
     * Gets the value of the modelDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelDescription() {
        return modelDescription;
    }

    /**
     * Sets the value of the modelDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelDescription(String value) {
        this.modelDescription = value;
    }

    /**
     * Gets the value of the engineDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineDescription() {
        return engineDescription;
    }

    /**
     * Sets the value of the engineDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineDescription(String value) {
        this.engineDescription = value;
    }

    /**
     * Gets the value of the exteriorColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorColor() {
        return exteriorColor;
    }

    /**
     * Sets the value of the exteriorColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorColor(String value) {
        this.exteriorColor = value;
    }

    /**
     * Gets the value of the vin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVin() {
        return vin;
    }

    /**
     * Sets the value of the vin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVin(String value) {
        this.vin = value;
    }

    /**
     * Gets the value of the licPlate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicPlate() {
        return licPlate;
    }

    /**
     * Sets the value of the licPlate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicPlate(String value) {
        this.licPlate = value;
    }

    /**
     * Gets the value of the licPlateState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicPlateState() {
        return licPlateState;
    }

    /**
     * Sets the value of the licPlateState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicPlateState(String value) {
        this.licPlateState = value;
    }

    /**
     * Gets the value of the licPlateExpDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLicPlateExpDate() {
        return licPlateExpDate;
    }

    /**
     * Sets the value of the licPlateExpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLicPlateExpDate(XMLGregorianCalendar value) {
        this.licPlateExpDate = value;
    }

    /**
     * Gets the value of the damageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDamageDescription() {
        return damageDescription;
    }

    /**
     * Sets the value of the damageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDamageDescription(String value) {
        this.damageDescription = value;
    }

    /**
     * Gets the value of the mileage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMileage() {
        return mileage;
    }

    /**
     * Sets the value of the mileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMileage(Integer value) {
        this.mileage = value;
    }
    
    /**
     * customized method to verify content
     */
    
    public boolean equals(VehicleInfoType other){
    	if (other == null || other.getClass() != getClass()) {
			return false;
		}
    	
    	List<String> diffs = new ArrayList<String>();

    	if (!damageDescription.equals(other.getDamageDescription())){
    		diffs.add(">>"+damageDescription);
    		diffs.add("<<"+other.getDamageDescription());
    	}
    	
    	if (!engineDescription.equals(other.getEngineDescription())){
    		diffs.add(">>"+engineDescription);
    		diffs.add("<<"+other.getEngineDescription());
    	}
    	
    	if (!exteriorColor.equals(other.getExteriorColor())){
    		diffs.add(">>"+exteriorColor);
    		diffs.add("<<"+other.getExteriorColor());
    	}
    	
    	if (!exteriorColor.equals(other.getExteriorColor())){
    		diffs.add(">>"+licPlate);
    		diffs.add("<<"+licPlate);
    	}
    	
    	if (!licPlateExpDate.toGregorianCalendar().getTime().equals(other.getLicPlateExpDate().toGregorianCalendar().getTime())){
    		diffs.add(">>"+licPlateExpDate.toString());
    		diffs.add("<<"+other.getLicPlateExpDate().toString());
    	}
    	
    	if (!licPlateState.equals(other.getLicPlateState())){
    		diffs.add(">>"+licPlateState);
    		diffs.add("<<"+other.getLicPlateState());
    	}
    	
    	if (!makeDescription.equals(other.getMakeDescription())){
    		diffs.add(">>"+makeDescription);
    		diffs.add("<<"+other.getMakeDescription());
    	}
    	
    	if (!mileage.equals(other.getMileage())){
    		diffs.add(">>"+mileage);
    		diffs.add("<<"+other.getMileage());
    	}
    	
    	if (!modelYear.equals(other.modelYear)){
    		
    	}
    	
    	for (String diff : diffs){
    		System.out.println(diff);
    	}
    	
    	return damageDescription.equals(other.getDamageDescription()) &&
    		   engineDescription.equals(other.getEngineDescription()) &&
    		   exteriorColor.equals(other.getExteriorColor()) &&
    		   licPlate.equals(other.getLicPlate()) && 
    		   licPlateExpDate.toGregorianCalendar().getTime().equals(other.getLicPlateExpDate().toGregorianCalendar().getTime()) &&
    		   licPlateState.equals(other.getLicPlateState()) &&
    		   makeDescription.equals(other.getMakeDescription()) &&
    		   mileage.equals(other.getMileage()) &&
    		   modelDescription.equals(other.getModelDescription()) &&
    		   modelYear.equals(other.getModelYear()) &&
    		   vin.equals(other.getVin());
    }
    
    public void display(){
    	System.out.println("DamageDescription: " + damageDescription);
    	System.out.println("EngineDescription: " + engineDescription);
    	System.out.println("ExteriorColor: " + exteriorColor);
    	System.out.println("LicPlate: " + licPlate);
    	System.out.println("LicPlateState: " + licPlateState);
    	System.out.println("LicPlateExpDate: " + licPlateExpDate.toString());
    	System.out.println("MakeDescription: " + makeDescription);
    	System.out.println("Mileage: " + mileage);
    	System.out.println("ModelDescription: " + modelDescription);
    	System.out.println("ModelYear: " + modelYear);
    	System.out.println("Vin: " + vin);
    }
    
    public void updateWithInstance(VehicleInfoType other){
    	
    	if (other.damageDescription != null){
    		damageDescription = other.damageDescription;
    	}
    	
    	if (other.engineDescription != null){
    		engineDescription = other.engineDescription;
    	}
    	
    	if (other.exteriorColor != null) {
    		exteriorColor = other.exteriorColor;
    	}
    	
    	if (other.licPlate != null){
    		licPlate = other.licPlate;
    	}
    	
    	if (other.licPlateExpDate != null){
    		licPlateExpDate = (XMLGregorianCalendar) other.licPlateExpDate.clone();
    	}
    	
    	if (other.licPlateState != null){
    		licPlateState = other.licPlateState;
    	}
    	
    	if (other.makeDescription != null){
    		makeDescription = other.makeDescription;
    	}
    	
    	if (other.mileage != null){
    		mileage = other.mileage;
    	}
    	
    	if (other.modelDescription != null){
    		modelDescription = other.modelDescription;
    	}
    	
    	if (other.modelYear != null){
    		modelYear = other.modelYear;
    	}
    	
    	if (other.vin != null){
    		vin = other.vin;
    	}
    }
}

